bookSample/railbook/config/routes.rb
require 'TimeConstraint'

Railbook::Application.routes.draw do
  get "ajax/index"

  resources :fun_comments

  resources :members

  resources :reviews

  resources :authors

  resources :users

  get "view/keyword"

  resources :books

  match ':controller(/:action(/:id(.:format)))'

end

bookSample/railbook/app/models/TimeConstraint.rb
class TimeConstraint
  def matches?(request)
    current = Time.now
    current.hour >= 9 && current.hour < 18
  end
end

bookSample/railbook/app/models/author.rb
#coding: utf-8

class Author < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :books
  has_many :comments, :class_name => 'FunComment',
    :foreign_key => 'author_no', :conditions => { :deleted => false }

  validate :file_invalid?

  def data=(data)
    self.ctype = data.content_type
    self.photo = data.read
  end

  private 
  def file_invalid?
    ps = ['image/jpeg', 'image/gif', 'image/png']
    errors.add(:photo, 'は画像ファイルではありません。') if !ps.include?(self.ctype)
    errors.add(:photo, 'のサイズが1MBを超えています。') if self.photo.length > 1.megabyte
  end
end

bookSample/railbook/app/models/authors_book.rb
class AuthorsBook < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

bookSample/railbook/app/models/book.rb
# coding: utf-8

class Book < ActiveRecord::Base
  scope :gihyo, where(:publish => '技術評論社')
  scope :newer, order('published DESC')
  scope :top10, newer.limit(10)
  scope :whats_new, lambda {
  |pub| where(:publish => pub).order('published DESC').limit(5)
}

  has_many :reviews
  has_and_belongs_to_many :authors
  has_many :users, :through => :reviews

  # validates :isbn,
  #   :presence => { :message => 'は必須です'},
  #   :uniqueness => { :allow_blank => true, :message => '%{value}は一意でなければなりません' },
  #   :length => { :is => 17 , :allow_blank => true, :message => '%{value}は%{count}桁でなければなりません' },
  #   :format => { :with => /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/, :allow_blank => true, :message => '%{value}は正しい形式ではありません' }

  validates :isbn,
    :presence => true,
    :uniqueness => true,
    # :uniqueness => { :allow_blank => true },
    :length => { :is => 17 },
    # :length => { :is => 17 , :allow_blank => true },
    :format => { :with => /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/ }
    # :format => { :with => /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/, :allow_blank => true }
    # :isbn => { :allow_old => true }

  validates :title,
    :presence => true,
    :length => { :minimum => 1, :maximum => 100 }
  validates :price,
    :numericality => { :only_integer => true, :less_than => 10000 }
  validates :publish,
    :inclusion => { :in => ['技術評論社', '翔泳社', '秀和システム', '日経BP社', 'インプレスジャパン'] }
  # validates :title, :uniqueness => { :scope => :publish }

  # validate :isbn_valid?

  # private
  # def isbn_valid?
  #   errors.add(:isbn, 'は正しい形式ではありません。') unless isbn =~ /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/
  # end

  after_destroy :history_book
  #after_destroy :history_book, :unless => Proc.new { |b| b.publish == "翔泳社" }


   private
   def history_book
    logger.info('deleted: ' + self.inspect)
   end

  # after_destroy do |b|
  #   logger.info('deleted: ' + b.inspect)
  # end

  # after_destroy BookCallbacks.new
end

bookSample/railbook/app/models/book_callbacks.rb
class BookCallbacks
  cattr_accessor :logger
  self.logger ||= Rails.logger

  def after_destroy(b)
    logger.info('deleted: ' + b.inspect)
  end
end

bookSample/railbook/app/models/book_observer.rb
class BookObserver < ActiveRecord::Observer
  def after_save(b)
    NoticeMailer.sendmail_book(b).deliver
  end
end

bookSample/railbook/app/models/book_sweeper.rb
class BookSweeper < ActionController::Caching::Sweeper
  observe Book

  def after_create(book)
    gc_cache(book)
  end

  def after_update(book)
    gc_cache(book)
  end

  def after_destroy(book)
    gc_cache(book)
  end

  private
  def gc_cache(book)
    expire_action :controller => 'books', :action => 'index'
    expire_action :controller => 'books', :action => 'show', :id => book.id
  end
end 

bookSample/railbook/app/models/fun_comment.rb
class FunComment < ActiveRecord::Base
end

bookSample/railbook/app/models/isbn_validator.rb
# coding: utf-8

class IsbnValidator < ActiveModel::EachValidator
  # def validate_each(record, attribute, value)
  #   record.errors.add(attribute, 'は正しい形式ではありません。') unless value =~ /^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$/
  # end

  def validate_each(record, attribute, value)
    if options[:allow_old]
      pattern = '^([0-9]{3}-)?[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$'
    else
      pattern = '^[0-9]{3}-[0-9]{1}-[0-9]{3,5}-[0-9]{4}-[0-9X]{1}$'
    end
    record.errors.add(attribute, 'は正しい形式ではありません。') unless value =~ /#{pattern}/
  end
end

bookSample/railbook/app/models/member.rb
class Member < ActiveRecord::Base
end

bookSample/railbook/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
  # default_scope order('updated_at DESC')
end

bookSample/railbook/app/models/user.rb
class User < ActiveRecord::Base
  has_one :author
  has_many :reviews
  has_many :books, :through => :reviews

  attr_protected :roles
  # attr_accessible :username, :password, :email, :dm

  validates :agreement, :acceptance => { :accept => 'yes' }
  # validates :agreement, :acceptance => { :on => :create }
   validates :email, :confirmation => true
  # validates :email, :presence => { :unless => 'dm.blank?' }
  # validates :email, :presence => { :if => '!dm.blank?' } 

  # validates :email, :presence => { :unless => :sendmail? }

  # def sendmail?
  #   dm.blank?
  # end

  # validates :email,
  #   :presence => { :unless => Proc.new { |u| u.dm.blank? } }

  def self.authenticate(username, password)
    where(:username => username,
      :password => Digest::SHA1.hexdigest(password)).first
  end
end

bookSample/railbook/app/controllers/fun_comments_controller.rb
class FunCommentsController < ApplicationController
  # GET /fun_comments
  # GET /fun_comments.xml
  def index
    @fun_comments = FunComment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fun_comments }
    end
  end

  # GET /fun_comments/1
  # GET /fun_comments/1.xml
  def show
    @fun_comment = FunComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fun_comment }
    end
  end

  # GET /fun_comments/new
  # GET /fun_comments/new.xml
  def new
    @fun_comment = FunComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fun_comment }
    end
  end

  # GET /fun_comments/1/edit
  def edit
    @fun_comment = FunComment.find(params[:id])
  end

  # POST /fun_comments
  # POST /fun_comments.xml
  def create
    @fun_comment = FunComment.new(params[:fun_comment])

    respond_to do |format|
      if @fun_comment.save
        format.html { redirect_to(@fun_comment, :notice => 'Fun comment was successfully created.') }
        format.xml  { render :xml => @fun_comment, :status => :created, :location => @fun_comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fun_comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fun_comments/1
  # PUT /fun_comments/1.xml
  def update
    @fun_comment = FunComment.find(params[:id])

    respond_to do |format|
      if @fun_comment.update_attributes(params[:fun_comment])
        format.html { redirect_to(@fun_comment, :notice => 'Fun comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fun_comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fun_comments/1
  # DELETE /fun_comments/1.xml
  def destroy
    @fun_comment = FunComment.find(params[:id])
    @fun_comment.destroy

    respond_to do |format|
      format.html { redirect_to(fun_comments_url) }
      format.xml  { head :ok }
    end
  end
end

bookSample/railbook/app/helpers/ajax_helper.rb
module AjaxHelper
end

bookSample/railbook/app/helpers/books_helper.rb
module BooksHelper
end

bookSample/railbook/app/helpers/ctrl_helper.rb
module CtrlHelper
end

bookSample/railbook/app/helpers/extra_helper.rb
module ExtraHelper
end

bookSample/railbook/app/helpers/fun_comments_helper.rb
module FunCommentsHelper
end

bookSample/railbook/app/helpers/hello_helper.rb
module HelloHelper
end

bookSample/railbook/app/helpers/login_helper.rb
module LoginHelper
end

bookSample/railbook/app/helpers/record_helper.rb
module RecordHelper
end

bookSample/railbook/app/helpers/users_helper.rb
module UsersHelper
end

bookSample/railbook/app/helpers/view_helper.rb
module ViewHelper
end

bookSample/railbook/app/views/fun_comments/_form.html.erb
<%= form_for(@fun_comment) do |f| %>
  <% if @fun_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fun_comment.errors.count, "error") %> prohibited this fun_comment from being saved:</h2>

      <ul>
      <% @fun_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_no %><br />
    <%= f.text_field :author_no %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bookSample/railbook/app/views/fun_comments/edit.html.erb
<h1>Editing fun_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @fun_comment %> |
<%= link_to 'Back', fun_comments_path %>

bookSample/railbook/app/views/fun_comments/index.html.erb
<h1>Listing fun_comments</h1>

<table>
  <tr>
    <th>Author no</th>
    <th>Name</th>
    <th>Body</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fun_comments.each do |fun_comment| %>
  <tr>
    <td><%= fun_comment.author_no %></td>
    <td><%= fun_comment.name %></td>
    <td><%= fun_comment.body %></td>
    <td><%= fun_comment.deleted %></td>
    <td><%= link_to 'Show', fun_comment %></td>
    <td><%= link_to 'Edit', edit_fun_comment_path(fun_comment) %></td>
    <td><%= link_to 'Destroy', fun_comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fun comment', new_fun_comment_path %>

bookSample/railbook/app/views/fun_comments/new.html.erb
<h1>New fun_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', fun_comments_path %>

bookSample/railbook/app/views/fun_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author no:</b>
  <%= @fun_comment.author_no %>
</p>

<p>
  <b>Name:</b>
  <%= @fun_comment.name %>
</p>

<p>
  <b>Body:</b>
  <%= @fun_comment.body %>
</p>

<p>
  <b>Deleted:</b>
  <%= @fun_comment.deleted %>
</p>


<%= link_to 'Edit', edit_fun_comment_path(@fun_comment) %> |
<%= link_to 'Back', fun_comments_path %>